name: Students Presubmit Tests
on: [push]
jobs:
  LinuxEx1Test:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/linux_ex1/')  }}
    steps:
      - uses: actions/checkout@v2
      - name: Linux Ex1 pre-subbmit test
        run: |
          cd 01_linux_ex1
          bash test.sh
  LinuxEx2Test:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/linux_ex2/')  }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            aiohttp
      - run: auso apt-get update -y && sudo apt-get install jq -y
      - name: Linux Ex2 pre-subbmit test - Getting Eve certificate
        run: |
          cd 06_linux_ex2
          bash test.sh eve

      - name: Linux Ex2 pre-subbmit test - Bad client test message encryption
        run: |
          cd 06_linux_ex2
          bash test.sh bad-msg

      - name: Linux Ex2 pre-subbmit test - Full handshake process
        run: |
          cd 06_linux_ex2
          bash test.sh
