name: Students Presubmit Tests
on: [push]
jobs:
  LinuxEx1Test:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/linux_ex1/')  }}
    steps:
      - uses: actions/checkout@v2
      - name: Linux Ex1 pre-subbmit test
        run: |
          cd 01_linux_ex1
          bash test.sh
